version: '3'
services:
  attendance_generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: attendance_generator_image
    volumes:
      - ./script:/app/script
      - ./input:/app/input
      - ./output:/app/output